_TEAMS = {
    "Anaheim Angels": "Angels",
    "Angels": "Angels",
    "Arizona Diamondbacks": "Dbacks",
    "Athletics": "Athletics",
    "Atlanta Braves": "Braves",
    "Baltimore Orioles": "Orioles",
    "Boston Red Sox": "Red Sox",
    "Brooklyn Dodgers": "Dodgers",
    "California Angels": "Angels",
    "California Los Angeles Angels": "Angels",
    "Chicago Cubs": "Cubs",
    "Chicago White Sox": "White Sox",
    "Cincinatti Reds": "Reds",
    "Cincinnati Reds": "Reds",
    "Cleveland": "Guardians",
    "Cleveland Guardians": "Guardians",
    "Colorado Rockies": "Rockies",
    "Detroit Tigers": "Tigers",
    "Florida Marlins": "Marlins",
    "Homestead": "Homestead",
    "Houston Astros": "Astros",
    "Kanas City Royals": "Royals",
    "Kansas City Royals": "Royals",
    "Los Angeles Angels": "Angels",
    "Los Angeles Dodgers": "Dodgers",
    "Miami Marlins": "Marlins",
    "Milwaukee Braves": "Braves",
    "Milwaukee Brewers": "Brewers",
    "Minnesota Twins": "Twins",
    "Montreal Expos": "Expos",
    "Montréal Expos": "Expos",
    "National League": "NL",
    "New York Giants": "Giants",
    "New York Mets": "Mets",
    "New York Yankees": "Yankees",
    "Oakland Athletics": "Oakland",
    "Philadelphia Phillies": "Phillies",
    "Pittsburgh Pirates": "Pirates",
    "San Diego Padres": "Padres",
    "San Francisco Giants": "Giants",
    "Seattle Mariners": "Mariners",
    "St. Louis Browns": "Browns",
    "St. Louis Cardinals": "Cardinals",
    "Tampa Bay Devil Rays": "Rays",
    "Tampa Bay Rays": "Rays",
    "Texas Rangers": "Rangers",
    "Toronto Blue Jays": "Jays",
    "Washington Nationals": "Nationals",
    "Washington Senators": "Senators",
}


def shorten_team_name(long_name: str) -> str:
    return _TEAMS.get(long_name, None)
